# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - QuickSpeakWebTest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Verify build output
        run: |
          echo "=== Listing all files in workspace ==="
          ls -la
          echo "=== Checking .next directory ==="
          if [ -d ".next" ]; then
            ls -la .next
            du -sh .next
          else
            echo ".next directory is MISSING after build!"
          fi

      - name: Create deployment zip (includes hidden files like .next)
        run: |
          echo "Creating zip with .next included..."
          zip -r deploy.zip . \
            -x "node_modules/*" \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.log" \
            -x "deploy.zip" \
            -x ".next/cache/*"
          echo "Zip created successfully."

      - name: Inspect zip contents
        run: |
          echo "Zip contents (first 120 lines, looking for .next):"
          unzip -l deploy.zip | sed -n '1,120p' | grep -i ".next" || true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./artifact

      - name: List artifact folder (debug)
        run: ls -la ./artifact

      - name: Deploy to Azure Web App (zip)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "QuickSpeakWebTest"
          slot-name: "Production"
          package: ./artifact/deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CA5C60C301BB44CF9478B4E80A88A1FB }}
