name: Build and deploy Node.js app to Azure Web App - quickspeak

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: quickspeak

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production
          # Agrega tus variables NEXT_PUBLIC_* aquí:
          NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
          NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
          # NEXT_PUBLIC_OTRA_VAR: ${{ secrets.NEXT_PUBLIC_OTRA_VAR }}

      - name: Copy static files to standalone
        run: node copy-files.js

      - name: Create package.json for standalone
        run: |
          cd .next/standalone
          echo '{"dependencies":{},"scripts":{"start":"node server.js"}}' > package.json

      - name: Upload standalone artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .next/standalone

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BD463C1C69B34E44AE9986C3F109694E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FDFD9DD69E74F66B800571209236B96 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC77FE3116484C3A96E5549E02CE291C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: Production
          package: .

